#!/bin/bash

# setup
PATH="${0%/*}/cross-compiler/bin:$PATH"
gcc() {
	i686-elf-gcc -Wall -ffreestanding -nostdlib -lgcc -ggdb $@
}
rm -rf obj/myos.bin obj/iso

# compiling and linking
gcc  src/boot.s  -o obj/myos.bin

# testing for multiboot
if ! grub-file --is-x86-multiboot obj/myos.bin
then
	echo Image is not multiboot!
	exit
fi

# out
cp obj/myos.bin out/myos.bin
# grub iso
if true
then
	mkdir -p obj/iso/boot/grub
	cp -f obj/myos.bin obj/iso/boot/myos.bin
	cp -f src/grub.cfg obj/iso/boot/grub/grub.cfg
	grub-mkrescue -o out/myos.iso obj/iso
fi

#qemu-system-i386 -d guest_errors -D qemu.log -kernel out/myos.bin
qemu-system-i386 -d guest_errors -D qemu.log -cdrom out/myos.iso
